version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: certificate_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=certificate_verification_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - cert_network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: certificate_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/certificate_verification_db
      - JWT_SECRET=docker_secret_jwt_key_2026
      - BLOCKCHAIN_RPC_URL=http://host.docker.internal:8545
      - BLOCKCHAIN_CHAIN_ID=31337
    depends_on:
      - mongodb
    networks:
      - cert_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: certificate_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - cert_network

volumes:
  mongodb_data:

networks:
  cert_network:
    driver: bridge
